# Generated by Django 3.2 on 2022-02-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDjangoModel',
            fields=[
                ('vat_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(max_length=200)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressDjangoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=5)),
                ('cp', models.CharField(max_length=10)),
                ('poblation', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('obs', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customerdjangomodel')),
            ],
        ),
    ]
